=== leonmohan/humber-college-projects/Semester 3/XML/Classplan/classplan.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<!-- CODED BY: Leon Mohan -->
<!-- /////////////////////////////////// -->

<xs:schema attributeFormDefault="qualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="ClassPlan">
        <xs:complexType>
            <xs:sequence>
                <!-- Main table headers -->
                <xs:element type="xs:string" name="ModuleHeader"/>
                <xs:element type="xs:string" name="TopicHeader"/>
                <xs:element type="xs:string" name="ActivityHeader"/>
                <xs:element type="xs:string" name="WeightHeader"/>
                <!-- Modules (aka. contents of the main table) -->
                <xs:element name="WeekModule" maxOccurs="14"> <!-- I am setting this to 14 because the document says it should a 14 week plan. -->
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="Week"/>
                            <xs:element type="xs:string" name="ModuleName"/>
                            <xs:element name="Topic" maxOccurs="unbounded" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="TopicInformation"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Activity" maxOccurs="unbounded" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="ActivityName"/>
                                        <xs:element type="xs:string" name="Weight"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <!-- Summary table -->
                <xs:element name="Summary">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="SummaryHeader"/>
                            <xs:element name="Labs" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="Name"/>
                                        <xs:element type="xs:string" name="Weight"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Quizzes" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="Name"/>
                                        <xs:element type="xs:string" name="Weight"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Assignments" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="Name"/>
                                        <xs:element type="xs:string" name="Weight"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Projects" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="Name"/>
                                        <xs:element type="xs:string" name="Weight"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Total" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="Name"/>
                                        <xs:element type="xs:string" name="Weight"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== leonmohan/humber-college-projects/Semester 3/XML/Classplan/classplan.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- CODED BY: Leon Mohan -->
<!-- /////////////////////////////////// -->

<?xml-stylesheet type="text/xsl" href="classplan.xslt" ?>

<ClassPlan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="classplan.xsd">
    <!--Main table's header-->
    <ModuleHeader>Modules/Week#</ModuleHeader>
    <TopicHeader>Topics and Readings</TopicHeader>
    <ActivityHeader>Class Activity</ActivityHeader>
    <WeightHeader>Weight</WeightHeader>
    
    <!-- Modules (aka. contents of the main table) -->
    <WeekModule>
        <Week>1</Week>
        <ModuleName>Basic XML</ModuleName>
        <Topic>
            <TopicInformation>Review course objectives, topics, assignments, policies</TopicInformation>
        </Topic>
        <Topic>
            <TopicInformation>Explain the structure of an XML Document</TopicInformation>
        </Topic>
        <Topic>
            <TopicInformation>Define the role of XML in web development</TopicInformation>
        </Topic>
        <Topic>
            <TopicInformation>Discover information Hierarchies</TopicInformation>
        </Topic>
        <Topic>
            <TopicInformation>Identify well-formed XML</TopicInformation>
        </Topic>
        <Topic>
            <TopicInformation>Identify valid XML syntax</TopicInformation>
        </Topic>
        <Activity>
            <ActivityName>Lab Activity(1)</ActivityName>
            <Weight>2%</Weight>
        </Activity>
    </WeekModule>
    <WeekModule>
        <Week>2</Week>
        <ModuleName>XML Document, and DTD</ModuleName>
        <Topic>
            <TopicInformation>Explain the structure of an XML Document</TopicInformation>
        </Topic>
        <Topic>
            <TopicInformation>Employ elements and attributes</TopicInformation>
        </Topic>
        <Topic>
            <TopicInformation>Define the structure and role of DTD</TopicInformation>
        </Topic>
        <Topic>
            <TopicInformation>Construct DTD for an XML document and create an XML document form DTD</TopicInformation>
        </Topic>
        <Topic>
            <TopicInformation>Validate XML documents using DTD</TopicInformation>
        </Topic>
        <Activity>
            <ActivityName>Lab Activity(2)</ActivityName>
            <Weight>3%</Weight>
        </Activity>
    </WeekModule>
    <WeekModule>
        <Week>3</Week>
        <ModuleName>XML Schema</ModuleName>
        <Topic>
            <TopicInformation>Define the usage of XML Namespace</TopicInformation>
        </Topic>
        <Topic>
            <TopicInformation>Define the structure and role of Schema for XML</TopicInformation>
        </Topic>
        <Topic>
            <TopicInformation>Construct Schema for an XML document and create an XML document from Schema</TopicInformation>
        </Topic>
        <Topic>
            <TopicInformation>Define the structure and role of XSLT in XML</TopicInformation>
        </Topic>
        <Topic>
            <TopicInformation>Compare XML Schema vs DTD</TopicInformation>
        </Topic>
        <Activity>
            <ActivityName>Lab Activity(3)</ActivityName>
            <Weight>2%</Weight>
        </Activity>
        <Activity>
            <ActivityName>Assignment(1)</ActivityName>
            <Weight>5%</Weight>
        </Activity>
    </WeekModule>
    
    <!-- Summary table and its contents -->
    <Summary>
        <SummaryHeader>Summary</SummaryHeader>
        <Labs>
            <Name>Labs</Name>
            <Weight>25%</Weight>
        </Labs>
        <Quizzes>
            <Name>Total for all Quizzes</Name>
            <Weight>25%</Weight>
        </Quizzes>
        <Assignments>
            <Name>Total for all Assignments</Name>
            <Weight>25%</Weight>
        </Assignments>
        <Projects>
            <Name>Total for all Projects</Name>
            <Weight>25%</Weight>
        </Projects>
        <Total>
            <Name>TOTAL</Name>
            <Weight>100%</Weight>
        </Total>
    </Summary>
</ClassPlan>
